import { getSupabaseClient, getSupabaseAnonClient } from './supabase-client';
import { SupabaseProductRepository } from './SupabaseProductRepository';
import { SupabaseCategoryRepository } from './SupabaseCategoryRepository';
import { SupabaseAdminRepository } from './SupabaseAdminRepository';
import { SupabaseClienteRepository } from './supabase-cliente.repository';
import { SupabaseEmpresaRepository } from './supabase-empresa.repository';
import { SupabasePromocionRepository } from './supabase-promocion.repository';
import { SupabasePedidoRepository } from './supabase-pedido.repository';
import { SupabaseMesaRepository } from './supabase-mesa.repository';
import { SupabaseMesaSesionRepository } from './supabase-mesa-sesion.repository';
import { SupabaseSuperAdminRepository } from './SupabaseSuperAdminRepository';
import { SupabaseTgtgRepository } from './supabase-tgtg.repository';
import { SupabaseDescuentoRepository } from './supabase-descuento.repository';
import { SupabaseMesaClientTokenRepository } from './supabase-mesa-client-token.repository';
import { SupabaseValoracionRepository } from './supabase-valoracion.repository';
import { SupabaseEmpleadoTpvRepository } from '../repositories/supabase-empleado-tpv.repository';
import { ProductUseCase } from '@/core/application/use-cases/product.use-case';
import { CategoryUseCase } from '@/core/application/use-cases/category.use-case';
import { ClienteUseCase } from '@/core/application/use-cases/cliente.use-case';
import { EmpresaUseCase } from '@/core/application/use-cases/empresa.use-case';
import { PedidoUseCase } from '@/core/application/use-cases/pedido.use-case';
import { MesaUseCase } from '@/core/application/use-cases/mesa.use-case';
import { MesaSesionUseCase } from '@/core/application/use-cases/mesa-sesion.use-case';
import { PromocionUseCase } from '@/core/application/use-cases/promocion.use-case';
import { TgtgUseCase } from '@/core/application/use-cases/tgtg.use-case';
import { AuthAdminUseCase } from '@/core/application/use-cases/auth-admin.use-case';
import { SuperAdminUseCase } from '@/core/application/use-cases/superadmin.use-case';
import { DescuentoUseCase } from '@/core/application/use-cases/descuento.use-case';
import { MesaClientTokenUseCase } from '@/core/application/use-cases/mesa-client-token.use-case';
import { ValoracionUseCase } from '@/core/application/use-cases/valoracion.use-case';
import { EmpleadoTpvLoginUseCase } from '@/core/application/use-cases/tpv/empleado-tpv-login.use-case';

const supabase = getSupabaseClient();
const supabaseAnon = getSupabaseAnonClient();

const productRepository = new SupabaseProductRepository(supabase);
const categoryRepository = new SupabaseCategoryRepository(supabase);
const adminRepository = new SupabaseAdminRepository(supabase, supabaseAnon);
const clienteRepository = new SupabaseClienteRepository(supabase);
export const empresaRepository = new SupabaseEmpresaRepository(supabase);
const promocionRepository = new SupabasePromocionRepository(supabase);
export const pedidoRepository = new SupabasePedidoRepository(supabase);
export const mesaRepository = new SupabaseMesaRepository(supabase);
export const mesaSesionRepository = new SupabaseMesaSesionRepository(supabase);
const superAdminRepository = new SupabaseSuperAdminRepository(supabase);
const tgtgRepository = new SupabaseTgtgRepository(supabase);
const descuentoRepository = new SupabaseDescuentoRepository(supabase);
const mesaClientTokenRepository = new SupabaseMesaClientTokenRepository(supabase);
export const valoracionRepository = new SupabaseValoracionRepository(supabase);
export const empleadoTpvRepository = new SupabaseEmpleadoTpvRepository();

// Public repository (anon key) for public-facing pages
export const empresaPublicRepository = new SupabaseEmpresaRepository(supabaseAnon);

// Use Cases (Clean Architecture - Application Layer)
export const productUseCase = new ProductUseCase(productRepository);
export const categoryUseCase = new CategoryUseCase(categoryRepository);
export const clienteUseCase = new ClienteUseCase(clienteRepository);
export const empresaUseCase = new EmpresaUseCase(empresaRepository);
export const pedidoUseCase = new PedidoUseCase(pedidoRepository, clienteRepository, productRepository, descuentoRepository, mesaSesionRepository);
export const mesaUseCase = new MesaUseCase(mesaRepository);
export const mesaSesionUseCase = new MesaSesionUseCase(mesaSesionRepository, mesaRepository);
export const promocionUseCase = new PromocionUseCase(promocionRepository, clienteRepository);
export const tgtgUseCase = new TgtgUseCase(tgtgRepository, clienteRepository);
export const authAdminUseCase = new AuthAdminUseCase(adminRepository);
export const superAdminUseCase = new SuperAdminUseCase(superAdminRepository);
export const descuentoUseCase = new DescuentoUseCase(descuentoRepository, empresaRepository);
export const mesaClientTokenUseCase = new MesaClientTokenUseCase(mesaClientTokenRepository, mesaSesionRepository);
export const valoracionUseCase = new ValoracionUseCase(valoracionRepository);
export const empleadoTpvLoginUseCase = new EmpleadoTpvLoginUseCase(empleadoTpvRepository);
