import { createClient } from "@supabase/supabase-js";
import dotenv from "dotenv";
import path from "node:path";

dotenv.config({ path: path.resolve(process.cwd(), ".env.local") });

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY!;

const supabase = createClient(supabaseUrl, supabaseServiceKey, {
  auth: {
    autoRefreshToken: false,
    persistSession: false,
  },
});

const productos = [
  {
    empresa_id: "f919fa96-06e8-41d3-b236-c02421775219",
    categoria_id: "cat-collares-raiz",
    titulo_es: "Collar Volcán",
    titulo_en: "Volcano Necklace",
    titulo_fr: "Collier Volcan",
    titulo_it: "Collana Vulcano",
    titulo_de: "Vulkan-Halskette",
    descripcion_es: "Collar con arena volcánica negra de Tenerife. Fuerza y carácter en cada grano.",
    descripcion_en: "Necklace with black volcanic sand from Tenerife. Strength and character in every grain.",
    descripcion_fr: "Collier avec sable volcanique noir de Tenerife. Force et caractère dans chaque grain.",
    descripcion_it: "Collana con sabbia vulcanica nera di Tenerife. Forza e carattere in ogni granello.",
    descripcion_de: "Halskette mit schwarzem Vulkansand aus Teneriffa. Kraft und Charakter in jedem Korn.",
    precio: "49.00",
    foto_url: null,
    es_especial: false,
    activo: true,
  },
  {
    empresa_id: "f919fa96-06e8-41d3-b236-c02421775219",
    categoria_id: "cat-collares-raiz",
    titulo_es: "Collar Origen",
    titulo_en: "Origin Necklace",
    titulo_fr: "Collier Origine",
    titulo_it: "Collana Origine",
    titulo_de: "Ursprung-Halskette",
    descripcion_es: "Colgante minimalista con cápsula de arena volcánica negra y cadena de plata 925.",
    descripcion_en: "Minimalist pendant with black volcanic sand capsule and 925 silver chain.",
    descripcion_fr: "Pendentif minimaliste avec capsule de sable volcanique noir et chaîne en argent 925.",
    descripcion_it: "Ciondolo minimalista con capsula di sabbia vulcanica nera e catena in argento 925.",
    descripcion_de: "Minimalistischer Anhänger mit schwarzer Vulkansandkapsel und 925 Silberkette.",
    precio: "55.00",
    foto_url: null,
    es_especial: false,
    activo: true,
  },
  {
    empresa_id: "f919fa96-06e8-41d3-b236-c02421775219",
    categoria_id: "cat-collares-raiz",
    titulo_es: "Collar Lava",
    titulo_en: "Lava Necklace",
    titulo_fr: "Collier Lave",
    titulo_it: "Collana Lava",
    titulo_de: "Lava-Halskette",
    descripcion_es: "Collar con doble cápsula de arena volcánica negra, símbolo de resiliencia y dualidad.",
    descripcion_en: "Necklace with double black volcanic sand capsule, symbol of resilience and duality.",
    descripcion_fr: "Collier avec double capsule de sable volcanique noir, symbole de résilience et dualité.",
    descripcion_it: "Collana con doppia capsula di sabbia vulcanica nera, simbolo di resilienza e dualità.",
    descripcion_de: "Halskette mit doppelter schwarzer Vulkansandkapsel, Symbol für Resilienz und Dualität.",
    precio: "65.00",
    foto_url: null,
    es_especial: true,
    activo: true,
  },
  {
    empresa_id: "f919fa96-06e8-41d3-b236-c02421775219",
    categoria_id: "cat-pulseras-raiz",
    titulo_es: "Pulsera Volcánica",
    titulo_en: "Volcanic Bracelet",
    titulo_fr: "Bracelet Volcanique",
    titulo_it: "Bracciale Vulcanico",
    titulo_de: "Vulkanisches Armband",
    descripcion_es: "Pulsera con cápsula de arena volcánica negra de Tenerife y cordón ajustable.",
    descripcion_en: "Bracelet with black volcanic sand capsule from Tenerife and adjustable cord.",
    descripcion_fr: "Bracelet avec capsule de sable volcanique noir de Tenerife et cordon ajustable.",
    descripcion_it: "Bracciale con capsula di sabbia vulcanica nera di Tenerife e cordino regolabile.",
    descripcion_de: "Armband mit schwarzer Vulkansandkapsel aus Teneriffa und verstellbarer Kordel.",
    precio: "35.00",
    foto_url: null,
    es_especial: false,
    activo: true,
  },
  {
    empresa_id: "f919fa96-06e8-41d3-b236-c02421775219",
    categoria_id: "cat-pulseras-raiz",
    titulo_es: "Pulsera Fuerza",
    titulo_en: "Strength Bracelet",
    titulo_fr: "Bracelet Force",
    titulo_it: "Bracciale Forza",
    titulo_de: "Kraft-Armband",
    descripcion_es: "Pulsera rígida de plata 925 con incrustación de arena volcánica negra. Para quienes no se rinden.",
    descripcion_en: "Rigid 925 silver bracelet with black volcanic sand inlay. For those who never give up.",
    descripcion_fr: "Bracelet rigide en argent 925 avec incrustation de sable volcanique noir. Pour ceux qui ne renoncent pas.",
    descripcion_it: "Bracciale rigido in argento 925 con intarsio di sabbia vulcanica nera. Per chi non si arrende.",
    descripcion_de: "Starres 925 Silberarmband mit schwarzem Vulkansandeinlage. Für diejenigen, die nie aufgeben.",
    precio: "59.00",
    foto_url: null,
    es_especial: false,
    activo: true,
  },
  {
    empresa_id: "f919fa96-06e8-41d3-b236-c02421775219",
    categoria_id: "cat-anillos-raiz",
    titulo_es: "Anillo Tierra",
    titulo_en: "Earth Ring",
    titulo_fr: "Bague Terre",
    titulo_it: "Anello Terra",
    titulo_de: "Erde-Ring",
    descripcion_es: "Anillo de plata 925 con canal de arena volcánica negra de Tenerife. Conexión con la tierra.",
    descripcion_en: "925 silver ring with black volcanic sand channel from Tenerife. Connection with the earth.",
    descripcion_fr: "Bague en argent 925 avec canal de sable volcanique noir de Tenerife. Connexion avec la terre.",
    descripcion_it: "Anello in argento 925 con canale di sabbia vulcanica nera di Tenerife. Connessione con la terra.",
    descripcion_de: "925 Silberring mit schwarzem Vulkansandkanal aus Teneriffa. Verbindung mit der Erde.",
    precio: "45.00",
    foto_url: null,
    es_especial: false,
    activo: true,
  },
  {
    empresa_id: "f919fa96-06e8-41d3-b236-c02421775219",
    categoria_id: "cat-anillos-raiz",
    titulo_es: "Anillo Carácter",
    titulo_en: "Character Ring",
    titulo_fr: "Bague Caractère",
    titulo_it: "Anello Carattere",
    titulo_de: "Charakter-Ring",
    descripcion_es: "Anillo ancho de plata 925 con arena volcánica negra sellada. Presencia y personalidad.",
    descripcion_en: "Wide 925 silver ring with sealed black volcanic sand. Presence and personality.",
    descripcion_fr: "Large bague en argent 925 avec sable volcanique noir scellé. Présence et personnalité.",
    descripcion_it: "Anello largo in argento 925 con sabbia vulcanica nera sigillata. Presenza e personalità.",
    descripcion_de: "Breiter 925 Silberring mit versiegeltem schwarzen Vulkansand. Präsenz und Persönlichkeit.",
    precio: "52.00",
    foto_url: null,
    es_especial: false,
    activo: true,
  },
  {
    empresa_id: "f919fa96-06e8-41d3-b236-c02421775219",
    categoria_id: "cat-pendientes-raiz",
    titulo_es: "Pendientes Obsidiana",
    titulo_en: "Obsidian Earrings",
    titulo_fr: "Boucles d'Oreilles Obsidienne",
    titulo_it: "Orecchini Ossidiana",
    titulo_de: "Obsidian-Ohrringe",
    descripcion_es: "Pendientes de botón con cápsula de arena volcánica negra y plata 925. Discretos y poderosos.",
    descripcion_en: "Stud earrings with black volcanic sand capsule and 925 silver. Discreet and powerful.",
    descripcion_fr: "Boucles puces avec capsule de sable volcanique noir et argent 925. Discrètes et puissantes.",
    descripcion_it: "Orecchini a lobo con capsula di sabbia vulcanica nera e argento 925. Discreti e potenti.",
    descripcion_de: "Ohrstecker mit schwarzer Vulkansandkapsel und 925 Silber. Dezent und kraftvoll.",
    precio: "38.00",
    foto_url: null,
    es_especial: false,
    activo: true,
  },
  {
    empresa_id: "f919fa96-06e8-41d3-b236-c02421775219",
    categoria_id: "cat-pendientes-raiz",
    titulo_es: "Pendientes Colada",
    titulo_en: "Lava Flow Earrings",
    titulo_fr: "Boucles d'Oreilles Coulée",
    titulo_it: "Orecchini Colata",
    titulo_de: "Lavastrom-Ohrringe",
    descripcion_es: "Pendientes colgantes con cápsula alargada de arena volcánica negra. Movimiento y fuerza.",
    descripcion_en: "Drop earrings with elongated black volcanic sand capsule. Movement and strength.",
    descripcion_fr: "Boucles pendantes avec capsule allongée de sable volcanique noir. Mouvement et force.",
    descripcion_it: "Orecchini pendenti con capsula allungata di sabbia vulcanica nera. Movimento e forza.",
    descripcion_de: "Hängeohrringe mit länglicher schwarzer Vulkansandkapsel. Bewegung und Kraft.",
    precio: "44.00",
    foto_url: null,
    es_especial: false,
    activo: true,
  },
  {
    empresa_id: "f919fa96-06e8-41d3-b236-c02421775219",
    categoria_id: "cat-collares-renacer",
    titulo_es: "Collar Alba",
    titulo_en: "Dawn Necklace",
    titulo_fr: "Collier Aube",
    titulo_it: "Collana Alba",
    titulo_de: "Morgenröte-Halskette",
    descripcion_es: "Collar con cápsula de arena clara natural de las Islas Canarias. Luz y nuevo comienzo.",
    descripcion_en: "Necklace with clear natural sand capsule from the Canary Islands. Light and new beginnings.",
    descripcion_fr: "Collier avec capsule de sable naturel clair des Îles Canaries. Lumière et nouveau départ.",
    descripcion_it: "Collana con capsula di sabbia naturale chiara delle Isole Canarie. Luce e nuovo inizio.",
    descripcion_de: "Halskette mit klarer Natursandkapsel von den Kanarischen Inseln. Licht und neuer Anfang.",
    precio: "49.00",
    foto_url: null,
    es_especial: false,
    activo: true,
  },
  {
    empresa_id: "f919fa96-06e8-41d3-b236-c02421775219",
    categoria_id: "cat-collares-renacer",
    titulo_es: "Collar Marea",
    titulo_en: "Tide Necklace",
    titulo_fr: "Collier Marée",
    titulo_it: "Collana Marea",
    titulo_de: "Gezeiten-Halskette",
    descripcion_es: "Collar con cápsula doble de arena clara canaria. El vaivén de la vida como inspiración.",
    descripcion_en: "Necklace with double clear Canarian sand capsule. The rhythm of life as inspiration.",
    descripcion_fr: "Collier avec double capsule de sable clair canarien. Le va-et-vient de la vie comme inspiration.",
    descripcion_it: "Collana con doppia capsula di sabbia chiara canaria. Il ritmo della vita come ispirazione.",
    descripcion_de: "Halskette mit doppelter klarer kanarischer Sandkapsel. Der Rhythmus des Lebens als Inspiration.",
    precio: "62.00",
    foto_url: null,
    es_especial: false,
    activo: true,
  },
  {
    empresa_id: "f919fa96-06e8-41d3-b236-c02421775219",
    categoria_id: "cat-collares-renacer",
    titulo_es: "Collar Horizonte",
    titulo_en: "Horizon Necklace",
    titulo_fr: "Collier Horizon",
    titulo_it: "Collana Orizzonte",
    titulo_de: "Horizont-Halskette",
    descripcion_es: "Colgante largo con arena clara natural. Para quienes miran siempre hacia adelante.",
    descripcion_en: "Long pendant with clear natural sand. For those who always look forward.",
    descripcion_fr: "Long pendentif avec sable naturel clair. Pour ceux qui regardent toujours vers l'avenir.",
    descripcion_it: "Ciondolo lungo con sabbia naturale chiara. Per chi guarda sempre avanti.",
    descripcion_de: "Langer Anhänger mit klarem Natursand. Für diejenigen, die immer nach vorne schauen.",
    precio: "55.00",
    foto_url: null,
    es_especial: true,
    activo: true,
  },
  {
    empresa_id: "f919fa96-06e8-41d3-b236-c02421775219",
    categoria_id: "cat-pulseras-renacer",
    titulo_es: "Pulsera Luz",
    titulo_en: "Light Bracelet",
    titulo_fr: "Bracelet Lumière",
    titulo_it: "Bracciale Luce",
    titulo_de: "Licht-Armband",
    descripcion_es: "Pulsera con cápsula de arena clara de las Islas Canarias y cordón ajustable blanco.",
    descripcion_en: "Bracelet with clear Canary Island sand capsule and white adjustable cord.",
    descripcion_fr: "Bracelet avec capsule de sable clair des Îles Canaries et cordon ajustable blanc.",
    descripcion_it: "Bracciale con capsula di sabbia chiara delle Isole Canarie e cordino regolabile bianco.",
    descripcion_de: "Armband mit klarer Kanarensandkapsel und weißer verstellbarer Kordel.",
    precio: "35.00",
    foto_url: null,
    es_especial: false,
    activo: true,
  },
  {
    empresa_id: "f919fa96-06e8-41d3-b236-c02421775219",
    categoria_id: "cat-pulseras-renacer",
    titulo_es: "Pulsera Calma",
    titulo_en: "Calm Bracelet",
    titulo_fr: "Bracelet Calme",
    titulo_it: "Bracciale Calma",
    titulo_de: "Ruhe-Armband",
    descripcion_es: "Pulsera rígida de plata 925 con arena clara canaria. Serenidad que se lleva contigo.",
    descripcion_en: "Rigid 925 silver bracelet with clear Canarian sand. Serenity you carry with you.",
    descripcion_fr: "Bracelet rigide en argent 925 avec sable clair canarien. Sérénité que vous portez avec vous.",
    descripcion_it: "Bracciale rigido in argento 925 con sabbia chiara canaria. Serenità che porti con te.",
    descripcion_de: "Starres 925 Silberarmband mit klarem kanarischem Sand. Gelassenheit, die du bei dir trägst.",
    precio: "59.00",
    foto_url: null,
    es_especial: false,
    activo: true,
  },
  {
    empresa_id: "f919fa96-06e8-41d3-b236-c02421775219",
    categoria_id: "cat-anillos-renacer",
    titulo_es: "Anillo Blanco",
    titulo_en: "White Ring",
    titulo_fr: "Bague Blanche",
    titulo_it: "Anello Bianco",
    titulo_de: "Weißer Ring",
    descripcion_es: "Anillo de plata 925 con canal de arena clara canaria. Pureza y transformación.",
    descripcion_en: "925 silver ring with clear Canarian sand channel. Purity and transformation.",
    descripcion_fr: "Bague en argent 925 avec canal de sable clair canarien. Pureté et transformation.",
    descripcion_it: "Anello in argento 925 con canale di sabbia chiara canaria. Purezza e trasformazione.",
    descripcion_de: "925 Silberring mit klarem kanarischem Sandkanal. Reinheit und Transformation.",
    precio: "45.00",
    foto_url: null,
    es_especial: false,
    activo: true,
  },
  {
    empresa_id: "f919fa96-06e8-41d3-b236-c02421775219",
    categoria_id: "cat-anillos-renacer",
    titulo_es: "Anillo Nueva Era",
    titulo_en: "New Era Ring",
    titulo_fr: "Bague Nouvelle Ère",
    titulo_it: "Anello Nuova Era",
    titulo_de: "Neue-Ära-Ring",
    descripcion_es: "Anillo apilable de plata 925 con arena clara. Simboliza el inicio de una nueva etapa.",
    descripcion_en: "Stackable 925 silver ring with clear sand. Symbolizes the beginning of a new stage.",
    descripcion_fr: "Bague empilable en argent 925 avec sable clair. Symbolise le début d'une nouvelle étape.",
    descripcion_it: "Anello da sovrapporre in argento 925 con sabbia chiara. Simboleggia l'inizio di una nuova fase.",
    descripcion_de: "Stapelbarer 925 Silberring mit klarem Sand. Symbolisiert den Beginn einer neuen Phase.",
    precio: "39.00",
    foto_url: null,
    es_especial: false,
    activo: true,
  },
  {
    empresa_id: "f919fa96-06e8-41d3-b236-c02421775219",
    categoria_id: "cat-pendientes-renacer",
    titulo_es: "Pendientes Espuma",
    titulo_en: "Sea Foam Earrings",
    titulo_fr: "Boucles d'Oreilles Écume",
    titulo_it: "Orecchini Schiuma",
    titulo_de: "Meeresschaum-Ohrringe",
    descripcion_es: "Pendientes de botón con arena clara natural canaria. Ligereza y elegancia discreta.",
    descripcion_en: "Stud earrings with clear natural Canarian sand. Lightness and discreet elegance.",
    descripcion_fr: "Boucles puces avec sable naturel clair canarien. Légèreté et élégance discrète.",
    descripcion_it: "Orecchini a lobo con sabbia naturale chiara canaria. Leggerezza ed eleganza discreta.",
    descripcion_de: "Ohrstecker mit klarem natürlichem kanarischem Sand. Leichtigkeit und dezente Eleganz.",
    precio: "38.00",
    foto_url: null,
    es_especial: false,
    activo: true,
  },
  {
    empresa_id: "f919fa96-06e8-41d3-b236-c02421775219",
    categoria_id: "cat-pendientes-renacer",
    titulo_es: "Pendientes Brisa",
    titulo_en: "Breeze Earrings",
    titulo_fr: "Boucles d'Oreilles Brise",
    titulo_it: "Orecchini Brezza",
    titulo_de: "Brise-Ohrringe",
    descripcion_es: "Pendientes colgantes con cápsula alargada de arena clara. Movimiento suave, energía positiva.",
    descripcion_en: "Drop earrings with elongated clear sand capsule. Gentle movement, positive energy.",
    descripcion_fr: "Boucles pendantes avec capsule allongée de sable clair. Mouvement doux, énergie positive.",
    descripcion_it: "Orecchini pendenti con capsula allungata di sabbia chiara. Movimento delicato, energia positiva.",
    descripcion_de: "Hängeohrringe mit länglicher klarer Sandkapsel. Sanfte Bewegung, positive Energie.",
    precio: "44.00",
    foto_url: null,
    es_especial: false,
    activo: true,
  },
  {
    empresa_id: "f919fa96-06e8-41d3-b236-c02421775219",
    categoria_id: "cat-ediciones-especiales",
    titulo_es: "Collar Dualidad",
    titulo_en: "Duality Necklace",
    titulo_fr: "Collier Dualité",
    titulo_it: "Collana Dualità",
    titulo_de: "Dualität-Halskette",
    descripcion_es: "Dos cápsulas en un mismo collar: arena volcánica negra y arena clara canaria. Raíz y Renacer unidos.",
    descripcion_en: "Two capsules in one necklace: black volcanic sand and clear Canarian sand. Root and Rebirth united.",
    descripcion_fr: "Deux capsules dans un même collier: sable volcanique noir et sable clair canarien. Racine et Renaissance réunis.",
    descripcion_it: "Due capsule in una collana: sabbia vulcanica nera e sabbia chiara canaria. Radice e Rinascita unite.",
    descripcion_de: "Zwei Kapseln in einer Halskette: schwarzer Vulkansand und klarer kanarischer Sand. Wurzel und Wiedergeburt vereint.",
    precio: "85.00",
    foto_url: null,
    es_especial: true,
    activo: true,
  },
  {
    empresa_id: "f919fa96-06e8-41d3-b236-c02421775219",
    categoria_id: "cat-ediciones-especiales",
    titulo_es: "Set Dualidad",
    titulo_en: "Duality Set",
    titulo_fr: "Parure Dualité",
    titulo_it: "Set Dualità",
    titulo_de: "Dualität-Set",
    descripcion_es: "Collar y pulsera con arena volcánica y arena clara. El equilibrio entre la fuerza y la luz.",
    descripcion_en: "Necklace and bracelet with volcanic and clear sand. The balance between strength and light.",
    descripcion_fr: "Collier et bracelet avec sable volcanique et sable clair. L'équilibre entre la force et la lumière.",
    descripcion_it: "Collana e bracciale con sabbia vulcanica e sabbia chiara. L'equilibrio tra forza e luce.",
    descripcion_de: "Halskette und Armband mit Vulkansand und klarem Sand. Die Balance zwischen Stärke und Licht.",
    precio: "110.00",
    foto_url: null,
    es_especial: true,
    activo: true,
  },
  {
    empresa_id: "f919fa96-06e8-41d3-b236-c02421775219",
    categoria_id: "cat-regalos",
    titulo_es: "Pack Regalo Raíz",
    titulo_en: "Root Gift Pack",
    titulo_fr: "Pack Cadeau Racine",
    titulo_it: "Pack Regalo Radice",
    titulo_de: "Wurzel-Geschenkset",
    descripcion_es: "Collar y tarjeta con mensaje de la Colección Raíz, presentados en caja artesanal de madera.",
    descripcion_en: "Necklace and message card from the Root Collection, presented in a handmade wooden box.",
    descripcion_fr: "Collier et carte message de la Collection Racine, présentés dans une boîte artisanale en bois.",
    descripcion_it: "Collana e biglietto con messaggio della Collezione Radice, presentati in una scatola artigianale in legno.",
    descripcion_de: "Halskette und Nachrichtenkarte aus der Wurzel-Kollektion, in einer handgefertigten Holzbox präsentiert.",
    precio: "69.00",
    foto_url: null,
    es_especial: false,
    activo: true,
  },
  {
    empresa_id: "f919fa96-06e8-41d3-b236-c02421775219",
    categoria_id: "cat-regalos",
    titulo_es: "Pack Regalo Renacer",
    titulo_en: "Rebirth Gift Pack",
    titulo_fr: "Pack Cadeau Renaissance",
    titulo_it: "Pack Regalo Rinascita",
    titulo_de: "Wiedergeburt-Geschenkset",
    descripcion_es: "Collar y tarjeta con mensaje de la Colección Renacer, presentados en caja artesanal de madera.",
    descripcion_en: "Necklace and message card from the Rebirth Collection, presented in a handmade wooden box.",
    descripcion_fr: "Collier et carte message de la Collection Renaissance, présentés dans une boîte artisanale en bois.",
    descripcion_it: "Collana e biglietto con messaggio della Collezione Rinascita, presentati in una scatola artigianale in legno.",
    descripcion_de: "Halskette und Nachrichtenkarte aus der Wiedergeburt-Kollektion, in einer handgefertigten Holzbox präsentiert.",
    precio: "69.00",
    foto_url: null,
    es_especial: false,
    activo: true,
  },
  {
    empresa_id: "f919fa96-06e8-41d3-b236-c02421775219",
    categoria_id: "cat-regalos",
    titulo_es: "Pack Regalo Dualidad",
    titulo_en: "Duality Gift Pack",
    titulo_fr: "Pack Cadeau Dualité",
    titulo_it: "Pack Regalo Dualità",
    titulo_de: "Dualität-Geschenkset",
    descripcion_es: "Set Dualidad completo con caja artesanal, tarjeta personalizada y bolsa de tela de lino.",
    descripcion_en: "Complete Duality Set with handmade box, personalized card and linen fabric bag.",
    descripcion_fr: "Set Dualité complet avec boîte artisanale, carte personnalisée et sac en tissu de lin.",
    descripcion_it: "Set Dualità completo con scatola artigianale, biglietto personalizzato e sacchetto in tessuto di lino.",
    descripcion_de: "Vollständiges Dualität-Set mit handgefertigter Box, personalisierter Karte und Leinenstoffbeutel.",
    precio: "135.00",
    foto_url: null,
    es_especial: true,
    activo: true,
  },
];

async function insertProducts() {
  console.log(`Inserting ${productos.length} products...`);

  const { data, error } = await supabase.from("productos").insert(productos).select();

  if (error) {
    console.error("Error inserting products:", error);
    process.exit(1);
  }

  console.log(`✅ Successfully inserted ${data?.length || 0} products`);
  console.log("Inserted IDs:", data?.map((p) => p.id).join(", "));
}

insertProducts();
